name: Dev Builders

on:
  push:
      branches:
        - dev
        - .+-dev
  pull_request:
      branches:
        - dev
        - .+-dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      backend-working-directory: ./backend
      deployment-path: backend
      frontend-working-directory: ./frontend
      CI: ""
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build frontend
      run: |
        npm ci
        npm run build
      working-directory: ${{env.frontend-working-directory}}

    - name: Build backend
      run: |
        npm ci
        npm install -g jest
      working-directory: ${{env.backend-working-directory}}
    
    - name: Test Backend
      run: npm test
      working-directory: ${{env.backend-working-directory}}
      
