# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Inkee JavaScript Linter

on: [push, pull_request]

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 8.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
