# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Inkee General CI

on: 
  push:
    branches:    
      - master 

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      backend-working-directory: ./backend
      frontend-working-directory: ./frontend
    strategy:
      matrix:
        node-version: [10.x, 8.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install
      run: |
        working-directory: ${{env.backend-working-directory}}
        npm install
    
    - name: npm test
      run: |
        working-directory: ${{env.backend-working-directory}}
        npm test 
      env:
        CI: true
      
    - name: npm build
      run: |
        working-directory: ${{env.frontend-working-directory}}
        npm run build --if-present
    
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
    
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    
    - name: Deploy to Heroku
      run: |
        working-directory: ${{env.backend-working-directory}}
        git push heroku HEAD:master -f
