name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - dev
      - .*-dev
  pull_request:
    branches:
      - master
      - dev
      - .*-dev

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    env:
      backend-working-directory: ./backend
      deployment-path: backend
      frontend-working-directory: ./frontend
      CI: ""

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - name: Build frontend
        run: |
          npm ci
          npm run build
        working-directory: ${{env.frontend-working-directory}}

      - name: Build backend
        run: |
          npm ci
        working-directory: ${{env.backend-working-directory}}

      - name: Run ESLint
        run: |
          npx eslint . --ext .ts,.tsx
          eslint . --ext .js,.jsx,.ts,.tsx
