name: Inkee CI
on: 
  push:
    branches:    
      - master 
jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      backend-working-directory: ./backend
      frontend-working-directory: ./frontend
      CI: ""
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build backend
      run: |
        npm ci
        npm install -g jest
      working-directory: ${{env.backend-working-directory}}
    
    - name: Test Backend
      run: npm test
      working-directory: ${{env.backend-working-directory}}
  
    - name: Build frontend build files
      run: |
        npm ci
        npm run build
      working-directory: ${{env.frontend-working-directory}}

    - name: Set Build Files
      run: |
        rm -rf backend/build
        mv frontend/build backend/.
    
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Commit Build Files
      id: commit
      if: steps.changes.outputs.changed == 1
      run: |
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Auto updating build files." -a
    
    - name: Push changes
      id: push
      if: steps.commit.outputs.status == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  
  release:
    needs: build
    if: needs.build.changes.outputs.changed == 0 || needs.build.push.outputs.status == 'success'
    runs-on: ubuntu-latest
    env:
      deployment-path: backend
      backend-working-directory: ./backend
      CI: ""
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy to Heroku
      run: |
        git init
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git add .
        git commit -am "Deploy"
        git push --force heroku master
        rm -rf .git
      working-directory: ${{env.backend-working-directory}}
