name: Inkee CI
on: 
  push:
    branches:    
      - master 
jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      backend-working-directory: ./backend
      deployment-path: backend
      frontend-working-directory: ./frontend
      CI: ""
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build backend
      run: |
        npm ci
        npm install -g jest
      working-directory: ${{env.backend-working-directory}}
    
    - name: Test Backend
      run: npm test
      working-directory: ${{env.backend-working-directory}}
  
    - name: Build frontend build files
      run: |
        npm ci
        npm run build
      working-directory: ${{env.frontend-working-directory}}

    - name: Set Build Files
      run: |
        rm -rf backend/build
        mv frontend/build backend/.
    
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Commit Build Files
      id: commit
      if: steps.changes.outputs.changed == 1
      run: |
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Auto updating build files." -a
    
    - name: Push changes
      id: push
      if: steps.commit.outcome == 'success'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
  deploy:
    needs: build
    if: needs.build.changes.outputs.changed == 0 || needs.build.push.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        id: heroku_deploy
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"
      - name: Send Success Message to Discord
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'A new version of {{ EVENT_PAYLOAD.repository.full_name }} has been deployed!'

